# Generated by Django 4.2.3 on 2024-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=45)),
                ('company_initials', models.CharField(max_length=5)),
                ('company_tin', models.CharField(max_length=18)),
                ('company_contact_no', models.CharField(max_length=8)),
                ('company_address', models.CharField(max_length=90)),
            ],
        ),
    ]
