# Generated by Django 4.2.3 on 2024-12-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departments_items_project_suppliers_voucherrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequestdetail',
            name='voucher_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.voucherrequest'),
        ),
    ]
