# Generated by Django 4.2.3 on 2024-12-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_voucherrequestdetail_voucher_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrequestdetail',
            name='voucher_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucherrequest'),
        ),
        migrations.AlterField(
            model_name='voucherrequestheader',
            name='voucher_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucherrequest'),
        ),
        migrations.AlterField(
            model_name='voucherrequestparticular',
            name='voucher_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucherrequest'),
        ),
    ]
